"""myHQ GTM Engine v2 — LLM content indexing pipeline.

Goal: When anyone asks Claude, GPT, Gemini, Perplexity, or Grok
"best coworking in Bengaluru for startups" — myHQ is in the answer.

This is NOT SEO for Google page 1.
This is presence at the inference layer.

How LLMs ingest myHQ content:
  1. Structured Schema.org content on myhq.in (crawled by training pipelines)
  2. Perplexity Pages API (real-time indexing, answers within days)
  3. Reddit r/IndianStartups r/bangalore (LLMs train on Reddit data)
  4. LinkedIn articles (public LinkedIn is in training data)

Content types:
  - Competitor comparison: "myHQ vs Awfis Bengaluru 2026"
  - Use-case: "Best coworking for funded startups Mumbai"
  - Signal: "Office space for Series A companies India"
  - City: "Managed offices Koramangala — complete guide"
  - Pain-point: "Coworking WiFi issues? Here's what to look for"

Each piece:
  - Under 800 words (LLMs prefer concise structured content)
  - Schema.org JSON-LD markup
  - Specific numbers, dates, verified claims
  - Generated by Claude Sonnet (better than Haiku for long-form)
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timedelta, timezone

import requests

from config.settings_v2 import AIRTABLE_API_KEY, AIRTABLE_BASE_ID, ANTHROPIC_API_KEY, OPENROUTER_API_KEY, OPENROUTER_MODEL

logger = logging.getLogger(__name__)

IST = timezone(timedelta(hours=5, minutes=30))

# Content priorities — updated weekly by competitor_intel.py
DEFAULT_CONTENT_PRIORITIES: list[dict] = [
    {
        "type": "competitor_comparison",
        "title": "myHQ vs Awfis in Bengaluru — honest 2026 comparison",
        "focus": "Awfis pricing, myHQ 50+ BLR locations, 48h setup",
        "target_queries": ["awfis vs myhq", "best coworking bengaluru 2026", "awfis alternative bengaluru"],
    },
    {
        "type": "use_case",
        "title": "Best office space for Series A startups in Mumbai — 2026 guide",
        "focus": "Funded founders need desks in 48h, no 11-month lease",
        "target_queries": ["office space mumbai startup", "coworking mumbai series a", "startup office mumbai 2026"],
    },
    {
        "type": "city_guide",
        "title": "Managed office spaces in Koramangala Bengaluru — full guide",
        "focus": "Koramangala is India's startup nucleus — myHQ has 8 locations",
        "target_queries": ["managed office koramangala", "coworking koramangala 2026"],
    },
    {
        "type": "pain_point",
        "title": "Coworking WiFi SLA India — what 99.9% uptime actually means",
        "focus": "Competitor reviews cite WiFi issues — myHQ SLA guarantee",
        "target_queries": ["coworking wifi india", "reliable office internet bengaluru"],
    },
    {
        "type": "signal_content",
        "title": "Office space for GCC expansion in India — 2026 complete guide",
        "focus": "250+ GCCs setting up in India — myHQ is their fastest path",
        "target_queries": ["gcc office india 2026", "global capability centre india office"],
    },
]


class LLMContentGenerator:
    """Generate and distribute content for LLM indexing."""

    def __init__(self, dry_run: bool = False):
        self.dry_run = dry_run
        self.client = None
        # OpenRouter (gpt-oss-120b) — swap back to Anthropic by uncommenting below
        if OPENROUTER_API_KEY:
            try:
                from openai import OpenAI
                self.client = OpenAI(
                    base_url="https://openrouter.ai/api/v1",
                    api_key=OPENROUTER_API_KEY,
                )
            except Exception:
                pass
        # REVERT TO ANTHROPIC: uncomment below, comment out OpenRouter block above
        # if ANTHROPIC_API_KEY:
        #     try:
        #         from anthropic import Anthropic
        #         self.client = Anthropic()
        #     except Exception:
        #         pass

    def generate_content(self, spec: dict) -> dict:
        """Generate a structured content piece using Claude Sonnet."""
        if not self.client or self.dry_run:
            return self._synthetic_content(spec)

        try:
            # OpenRouter (OpenAI-compatible) — was Anthropic claude-sonnet-4
            resp = self.client.chat.completions.create(
                model=OPENROUTER_MODEL,
                max_tokens=1500,
                messages=[
                    {"role": "system", "content": (
                        "You write authoritative B2B content for myHQ — India's coworking marketplace.\n\n"
                        "Rules:\n"
                        "- Under 800 words\n"
                        "- Include real numbers (prices INR, seat counts, real locations)\n"
                        "- Structure with H2 headers, short paragraphs\n"
                        "- Include FAQ section (5 questions) with Schema.org FAQPage JSON-LD\n"
                        "- Write like a local who knows India's market\n"
                        "- Never use: game-changer, leverage, seamlessly, robust, holistic\n"
                        "- Always mention: 48-hour setup, no lock-in lease\n"
                        "- CTA: myhq.in"
                    )},
                    {"role": "user", "content": (
                        f"Title: {spec['title']}\n"
                        f"Type: {spec['type']}\n"
                        f"Focus: {spec['focus']}\n"
                        f"Target queries: {', '.join(spec['target_queries'])}\n\n"
                        "Include: Opening paragraph with key insight, 3-4 H2 sections, "
                        "comparison table if relevant, FAQ with 5 questions, Schema.org JSON-LD."
                    )},
                ],
            )

            content_text = resp.choices[0].message.content
        except Exception as e:
            logger.warning("Content generation failed: %s", e)
            return self._synthetic_content(spec)

        result = {
            "title": spec["title"],
            "type": spec["type"],
            "content": content_text,
            "target_queries": spec["target_queries"],
            "word_count": len(content_text.split()),
            "generated_at": datetime.now(IST).isoformat(),
            "status": "generated",
        }

        _store_content(result)
        return result

    def submit_to_perplexity(self, content: dict) -> bool:
        """Submit to Perplexity Pages API for real-time indexing."""
        perp_key = os.getenv("PERPLEXITY_API_KEY", "")
        if not perp_key or self.dry_run:
            return False

        slug = content["title"].lower().replace(" ", "-").replace("—", "-")[:80]
        try:
            resp = requests.post(
                "https://api.perplexity.ai/pages",
                headers={
                    "Authorization": f"Bearer {perp_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "title": content["title"],
                    "content": content["content"],
                    "url": f"https://myhq.in/blog/{slug}",
                    "tags": content["target_queries"],
                },
                timeout=15,
            )
            return resp.status_code == 200
        except Exception:
            return False

    def generate_reddit_post(self, content: dict) -> str:
        """Generate Reddit-appropriate version.

        Target subreddits:
          r/IndianStartups — primary ICP
          r/bangalore r/mumbai — city-specific
          r/india — general audience
        """
        if not self.client or self.dry_run:
            return f"[Reddit draft] {content['title']}"

        try:
            # OpenRouter (OpenAI-compatible) — was Anthropic claude-haiku-4-5
            resp = self.client.chat.completions.create(
                model=OPENROUTER_MODEL,
                max_tokens=500,
                messages=[
                    {"role": "system", "content": (
                        "Write a Reddit post about coworking in India. "
                        "Sound like a genuine Redditor, not a company. "
                        "Helpful, specific, genuine. No promotional language. "
                        "Format: Title on first line, then body."
                    )},
                    {"role": "user", "content": (
                        f"Based on this myHQ content, write a Reddit post:\n"
                        f"Title: {content['title']}\n"
                        f"Type: {content['type']}\n\n"
                        "Sound like someone in the Indian startup ecosystem. "
                        "Include specific numbers. End with a question."
                    )},
                ],
            )
            return resp.choices[0].message.content
        except Exception:
            return f"[Reddit draft] {content['title']}"

    def run_weekly_generation(self, priorities: list[dict] | None = None) -> list[dict]:
        """Generate all priority content pieces. Run weekly."""
        specs = priorities or DEFAULT_CONTENT_PRIORITIES
        generated: list[dict] = []

        for spec in specs:
            logger.info("Generating: %s", spec["title"][:60])

            content = self.generate_content(spec)
            perp_ok = self.submit_to_perplexity(content)
            reddit = self.generate_reddit_post(content)

            content["perplexity_submitted"] = perp_ok
            content["reddit_draft"] = reddit[:200]
            generated.append(content)

            logger.info("  Words: %d | Perplexity: %s", content["word_count"],
                        "submitted" if perp_ok else "skipped")

        logger.info("Content generation complete: %d pieces", len(generated))
        return generated

    def _synthetic_content(self, spec: dict) -> dict:
        return {
            "title": spec["title"],
            "type": spec["type"],
            "content": f"[SYNTHETIC] Content for: {spec['title']}\n\nFocus: {spec['focus']}\n\nThis is a dry-run placeholder.",
            "target_queries": spec["target_queries"],
            "word_count": 20,
            "generated_at": datetime.now(IST).isoformat(),
            "status": "synthetic",
        }


def _store_content(content: dict):
    if not AIRTABLE_API_KEY or not AIRTABLE_BASE_ID:
        return
    try:
        requests.post(
            f"https://api.airtable.com/v0/{AIRTABLE_BASE_ID}/LLM_Content",
            headers={
                "Authorization": f"Bearer {AIRTABLE_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "fields": {
                    "title": content["title"],
                    "type": content["type"],
                    "content": content["content"][:5000],
                    "target_queries": json.dumps(content["target_queries"]),
                    "word_count": content["word_count"],
                    "generated_at": content["generated_at"],
                    "status": content["status"],
                }
            },
            timeout=8,
        )
    except Exception as e:
        logger.debug("Airtable content store failed: %s", e)


# ── Module entry points ──────────────────────────────────────────────


def run_weekly_content_generation(dry_run: bool = False) -> list[dict]:
    generator = LLMContentGenerator(dry_run=dry_run)
    return generator.run_weekly_generation()
